sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: EzsZwyr07Fn+3tTz9kEYsJb8zctslX7WF4EzZ4rDHLrj/AgN4cpUojn+V5ii8cSMZyqCRT97PxMIRTQUSD7T6Q+fpEl8NH+4rUns9NXaqqPsn5pPCNGDMAyuyL6bumA5fbMCN8p+P14dqLkhQCVq5XNjcC2TDSkGzo+chE1JCxN7fwjZaqyMXz60/s0slWdZCzb50Qatd+u3MBoesX5mP8y3s/iik4dtg1vBbZkS05Fm8aOH4wDhvLHWMTFonqv/9pXnWhRNgoTTg+RocpE2OseI39xZklQMFCd9WWlMUYezkzTwG3Bxg9j6plAAo4SykOtd4mubzWxBF1a92PF5dmtnNe6lfOV011f+XpQbFUea89u1okomDm3TDL9X87OY/vxdoZnuGtYsEJ6wDeZav+lMJXlNcpYu6KlccBoMof5Y8gxFsOwUG5OmvypQwWy8H+C4doZCEOSmC0tRowChq7yFB2TRqZDNDnUGv2AuUy7cL4ayrEVOurD/p7NyZFZEclKsQcp2+aKOW1YHtimZnTM+EJ/qFsZHHNdmLwmU506ghxC4KAdiapkndoHy+fjPXQJNcXmDUL4tRglOzDpAjhgiSWGq772W1DbP6/5BZl2OVAzM/pUMNIaxdALseOOleTChYnkb8aQ/kTdItJnXPKq3/2WliYFsAOmg+dHUf/s=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Copyright-Basics_4292
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy